name: DigitalOceanFastAPITemplateApp
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: dmancevo/DigitalOceanFastAPITemplateApp
  name: DigitalOceanFastAPITemplateApp